### ISSUE TITLE
Apple & Google Play Store Submissions - Action Needed

### ISSUE THREAD

**Issue by Sam-Drummer** [ntadmin/TheTurningApp#17]
Hi Neil,
I hope you're well. I'm just getting in touch via GitHub rather than pestering you on the phone on a Friday afternoon! 

We've attempted to submit the app to the Apple store today and it now seems that you will need to login to your Apple account and review the licence agreement before apps can be submitted to your account. Please see the images attached.

<img width="1110" alt="Account_-_Apple_Developer" src="https://user-images.githubusercontent.com/60933949/74549232-334a4880-4f47-11ea-9230-709cef9e7336.png">

<img width="1117" alt="Screenshot_14_02_2020__15_20" src="https://user-images.githubusercontent.com/60933949/74549245-380efc80-4f47-11ea-975c-fdfc152d7cb2.png">

We do have some credentials archived that may still be correct (as detailed below) and believe it is Yinka who has access to your top level developer account? 

Apple ID
Email barnabaspub1@gmail.com
Password Ephesians423

Please can you let me know when this has been done and we'll submit the app to Apple as needed.

We have also attempted to submit the app to the GooglePlay store in the hopes that we could glean some further information on why the app had been removed. Unfortunately this did not provide any details so it is imperative that someone accesses the turningbfoc@gmail.com email address to discover the reason why. We'll then be able to fix whatever issue it is before trying again. Please see below the message from the GP store. 

![App_releases_-_The_Turning_-_Google_Play_Console](https://user-images.githubusercontent.com/60933949/74550210-e8c9cb80-4f48-11ea-8b35-0100aa5db26b.jpg)

Are you able to look into this further and try to get some traction on this from Janet and Yinka - sorry to ask but Janet hasn't responded to my email as yet.

With many thanks,

Sam

**Comment by ntadmin** [comment]
Steps needed:

1. Yinka to turn on two factor authentication for his Apple account.

2. Yinka to log into Apple dev account and accept new t and c

3. Yinka to add Neil (neil@the-townsends.net) to fully authorised access to the account.



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ntadmin** [comment]
Yinka messages to this effect.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ntadmin** [comment]
Resolved.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
